services:
  primary:
    build:
      context: ./postgres
    container_name: primary
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - chat-net
    volumes:
      - ./postgres/primary:/etc/postgresql/conf
      - ./postgres/primary/repmgr_primary.conf:/etc/repmgr/repmgr.conf
    command: postgres -c config_file=/etc/postgresql/conf/postgresql.conf -c hba_file=/etc/postgresql/conf/pg_hba.conf

  replica:
    build:
      context: ./postgres
    container_name: replica
    depends_on:
      - primary
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    networks:
      - chat-net
    volumes:
      - ./postgres/replica:/etc/postgresql/conf
      - ./postgres/replica/repmgr_replica.conf:/etc/repmgr/repmgr.conf
    command: postgres -c config_file=/etc/postgresql/conf/postgresql.conf -c hba_file=/etc/postgresql/conf/pg_hba.conf

  pgpool:
    image: pgpool/pgpool
    container_name: pgpool
    ports:
      - "5000:5432"
    depends_on:
      - primary
      - replica
    networks:
      - chat-net
    volumes:
      - ./postgres/pgpool/pgpool.conf:/config/pgpool.conf
      - ./postgres/pgpool/pool_hba.conf:/config/pool_hba.conf
      - ./postgres/pgpool/failover.sh:/opt/pgpool-II/etc/failover.sh

  
  redis-master:
    image: redis:8
    container_name: redis-master
    ports:
      - "6379:6379"
    networks:
      - chat-net

  redis-slave:
    image: redis:8
    container_name: redis-slave
    ports:
      - "6380:6379"
    depends_on:
      - redis-master
    command: redis-server --replicaof redis-master 6379
    networks:
      - chat-net

  sentinel-1:
    image: redis:8
    container_name: sentinel-1
    depends_on:
      - redis-master
      - redis-slave
    ports:
      - "26379:26379"
    volumes:
      - ./redis/sentinel:/usr/local/etc/redis
    command: redis-server /usr/local/etc/redis/sentinel.conf --sentinel
    networks:
      - chat-net

  sentinel-2:
    image: redis:8
    container_name: sentinel-2
    depends_on:
      - redis-master
      - redis-slave
    ports:
      - "26380:26379"
    volumes:
      - ./redis/sentinel:/usr/local/etc/redis
    command: redis-server /usr/local/etc/redis/sentinel.conf --sentinel
    networks:
      - chat-net

  sentinel-3:
    image: redis:8
    container_name: sentinel-3
    depends_on:
      - redis-master
      - redis-slave
    ports:
      - "26381:26379"
    volumes:
      - ./redis/sentinel:/usr/local/etc/redis
    command: redis-server /usr/local/etc/redis/sentinel.conf --sentinel
    networks:
      - chat-net


  kafka1:
    image: confluentinc/cp-kafka:latest
    container_name: kafka1
    ports:
      - 9091:9091
    environment:
      CLUSTER_ID: "D1tH5zG4aV8cE2jP"
      KAFKA_CLUSTER_ID: "D1tH5zG4aV8cE2jP"
      KAFKA_BROKER_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_LISTENERS: "PLAINTEXT://kafka1:9091,CONTROLLER://kafka1:9093"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9091
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka1:9093,2@kafka2:9093,3@kafka3:9093"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_TRANSACTION_STATE_LOG_NUM_PARTITIONS: 4
    networks:
      - chat-net
  
  kafka2:
    image: confluentinc/cp-kafka:latest
    container_name: kafka2
    ports:
      - 9092:9092
    environment:
      CLUSTER_ID: "D1tH5zG4aV8cE2jP"
      KAFKA_CLUSTER_ID: "D1tH5zG4aV8cE2jP"
      KAFKA_BROKER_ID: 2
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_LISTENERS: "PLAINTEXT://kafka2:9092,CONTROLLER://kafka2:9093"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka1:9093,2@kafka2:9093,3@kafka3:9093"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_TRANSACTION_STATE_LOG_NUM_PARTITIONS: 4
    networks:
      - chat-net

  kafka3:
    image: confluentinc/cp-kafka:latest
    container_name: kafka3
    ports:
      - 9094:9094
    environment:
      CLUSTER_ID: "D1tH5zG4aV8cE2jP"
      KAFKA_CLUSTER_ID: "D1tH5zG4aV8cE2jP"
      KAFKA_BROKER_ID: 3
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_LISTENERS: "PLAINTEXT://kafka3:9094,CONTROLLER://kafka3:9093"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9094
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka1:9093,2@kafka2:9093,3@kafka3:9093"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_TRANSACTION_STATE_LOG_NUM_PARTITIONS: 4
    networks:
      - chat-net

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - 8090:8080
    environment:
      - KAFKA_CLUSTERS_0_NAME=local-kraft
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka1:9091,kafka2:9092,kafka3:9094
    networks:
      - chat-net


networks:
  chat-net:
    name: chat-net
    driver: bridge