spring:
  data:
    redis:
      host: localhost
      port: 6379

  r2dbc:
    url: r2dbc:postgresql://localhost:5000/postgres
    username: postgres
    password: postgres
    pool:
      initial-size: 5
      max-size: 20
