spring:
  data:
    redis:
      host: localhost
      port: 6379

  r2dbc:
    url: r2dbc:postgresql://localhost:5000/postgres
    username: postgres
    password: postgres
    pool:
      initial-size: 5
      max-size: 20

  kafka:
    bootstrap-servers: localhost:9091,localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: my-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
